

#' PHUSE RBM Working Group
#' Assessing the use of Quality Tolerance Limits (QTL) in the Pharma Industry

#' Goal:
#' 1. Clean the data from the QTL survey
#' 2. Generate the corresponding visual to support the 'whitepaper'.

#' Focus:
#' Work on selected questions/figures only. 

#' Author: Steven Ponce
#' Date: 2024-04-02



# 1. LOAD PACKAGES ---- 
pacman::p_load(tidyverse, here, janitor, lubridate, scales, ggtext, showtext, data.table)
pacman::p_load(ggdist, urbnthemes)


# source helper functions
source("03_functions/01_helper_functions.R")



# 2. READ IN THE DATA ----

#' Note:
#' Since the data was collected using Google Forms, the incoming raw data is
#' extremely messy. At this moment, it might be a good idea to:
#' - select the columns corresponding to a specific question,
#' - create a dataframe for each question, then proceed to clean the data,
#' - finally generate the visual. 


# loading the raw data (as is)
raw_data <- fread(file = "00_data/IN/qtl_survey_response.csv") |>
  clean_names()

# Question 03 ----
q3_raw <- raw_data |> 
  select(x3_which_functional_area_s_are_involved_in_trial_level_risk_based_approaches_to_quality_1_please_check_all_that_apply_1_please_see_ich_e6_r2_section_5_0_and_ich_e8_r1,
         other_2)


# Question 04 ----
q4_raw <- raw_data |> 
  select(x4_which_functional_area_leads_trial_level_risk_based_approaches_to_quality_please_check_only_one,
         other_3)


# Question 05 ----      
q5_raw <- raw_data |> 
  select(x5_are_there_any_trial_types_where_your_company_does_not_apply_risk_based_approaches_to_quality_please_select_all_that_apply_and_provide_comments_as_to_why_this_is_the_case,
         comment_why)


# Question 06 ----

### |- UPDATED -----

q6_raw <- raw_data |> 
  select(
    x6_which_aspects_of_risk_based_approaches_to_quality_does_your_company_apply_to_the_following_trial_types_please_check_all_that_apply_fih,
    x6_which_aspects_of_risk_based_approaches_to_quality_does_your_company_apply_to_the_following_trial_types_please_check_all_that_apply_phase_i_non_fih,
    x6_which_aspects_of_risk_based_approaches_to_quality_does_your_company_apply_to_the_following_trial_types_please_check_all_that_apply_phase_ii,
    x6_which_aspects_of_risk_based_approaches_to_quality_does_your_company_apply_to_the_following_trial_types_please_check_all_that_apply_phase_iii_regulatory_submission,
    x6_which_aspects_of_risk_based_approaches_to_quality_does_your_company_apply_to_the_following_trial_types_please_check_all_that_apply_phase_iii_follow_up,
    x6_which_aspects_of_risk_based_approaches_to_quality_does_your_company_apply_to_the_following_trial_types_please_check_all_that_apply_phase_iv
    )


# Question 07 ----

### |- UPDATED -----

q7_raw <- raw_data |> 
  select(
    x7_if_you_answered_yes_to_other_risk_based_approaches_used_in_question_6_please_identify_those_used_please_check_all_that_apply
    )



# Question 08 ----      

### |- UPDATED -----

q8_raw <- raw_data |> 
  select(
    x8_is_your_company_s_risk_based_approach_to_quality_applied_differently_depending_on_the_following_trial_atttributes_please_note_some_organizations_may_have_more_than_one_activity_that_is_tightly_integrated_across_multiple_elements_e_g_trial_size_and_phase_please_utilize_the_mixed_response_for_these_situations_identification_of_ct_qs,
    x8_is_your_company_s_risk_based_approach_to_quality_applied_differently_depending_on_the_following_trial_atttributes_please_note_some_organizations_may_have_more_than_one_activity_that_is_tightly_integrated_across_multiple_elements_e_g_trial_size_and_phase_please_utilize_the_mixed_response_for_these_situations_overall_implementation_of_qb_d,
    x8_is_your_company_s_risk_based_approach_to_quality_applied_differently_depending_on_the_following_trial_atttributes_please_note_some_organizations_may_have_more_than_one_activity_that_is_tightly_integrated_across_multiple_elements_e_g_trial_size_and_phase_please_utilize_the_mixed_response_for_these_situations_qt_ls_utilized,
    x8_is_your_company_s_risk_based_approach_to_quality_applied_differently_depending_on_the_following_trial_atttributes_please_note_some_organizations_may_have_more_than_one_activity_that_is_tightly_integrated_across_multiple_elements_e_g_trial_size_and_phase_please_utilize_the_mixed_response_for_these_situations_qt_ls_aligned_with_ct_qs,
    x8_is_your_company_s_risk_based_approach_to_quality_applied_differently_depending_on_the_following_trial_atttributes_please_note_some_organizations_may_have_more_than_one_activity_that_is_tightly_integrated_across_multiple_elements_e_g_trial_size_and_phase_please_utilize_the_mixed_response_for_these_situations_qtl_review_processes,
    x8_is_your_company_s_risk_based_approach_to_quality_applied_differently_depending_on_the_following_trial_atttributes_please_note_some_organizations_may_have_more_than_one_activity_that_is_tightly_integrated_across_multiple_elements_e_g_trial_size_and_phase_please_utilize_the_mixed_response_for_these_situations_frequency_of_qtl_review,
    x8_is_your_company_s_risk_based_approach_to_quality_applied_differently_depending_on_the_following_trial_atttributes_please_note_some_organizations_may_have_more_than_one_activity_that_is_tightly_integrated_across_multiple_elements_e_g_trial_size_and_phase_please_utilize_the_mixed_response_for_these_situations_communication_of_qtl_breaches,
    x8_is_your_company_s_risk_based_approach_to_quality_applied_differently_depending_on_the_following_trial_atttributes_please_note_some_organizations_may_have_more_than_one_activity_that_is_tightly_integrated_across_multiple_elements_e_g_trial_size_and_phase_please_utilize_the_mixed_response_for_these_situations_implementation_of_corrective_actions,
    x8_is_your_company_s_risk_based_approach_to_quality_applied_differently_depending_on_the_following_trial_atttributes_please_note_some_organizations_may_have_more_than_one_activity_that_is_tightly_integrated_across_multiple_elements_e_g_trial_size_and_phase_please_utilize_the_mixed_response_for_these_situations_reporting_significant_qtl_deviations_in_csr
  )



# Question 10 ----
q10_raw <- raw_data |> 
  select(
    x10_how_does_your_company_document_your_risk_based_approaches_to_quality_please_check_all_that_apply_the_goal_of_this_question_and_others_that_follow_with_similar_activities_regarding_ctq_s_qbd_is_to_understand_what_and_how_your_company_makes_links_if_any_from_these_activities_to_qtl_s_identification_of_ct_qs,
    x10_how_does_your_company_document_your_risk_based_approaches_to_quality_please_check_all_that_apply_the_goal_of_this_question_and_others_that_follow_with_similar_activities_regarding_ctq_s_qbd_is_to_understand_what_and_how_your_company_makes_links_if_any_from_these_activities_to_qtl_s_implementation_of_qb_d,
    x10_how_does_your_company_document_your_risk_based_approaches_to_quality_please_check_all_that_apply_the_goal_of_this_question_and_others_that_follow_with_similar_activities_regarding_ctq_s_qbd_is_to_understand_what_and_how_your_company_makes_links_if_any_from_these_activities_to_qtl_s_implementation_of_a_risk_strategy_3,
    x10_how_does_your_company_document_your_risk_based_approaches_to_quality_please_check_all_that_apply_the_goal_of_this_question_and_others_that_follow_with_similar_activities_regarding_ctq_s_qbd_is_to_understand_what_and_how_your_company_makes_links_if_any_from_these_activities_to_qtl_s_qt_ls_utilized,
    x10_how_does_your_company_document_your_risk_based_approaches_to_quality_please_check_all_that_apply_the_goal_of_this_question_and_others_that_follow_with_similar_activities_regarding_ctq_s_qbd_is_to_understand_what_and_how_your_company_makes_links_if_any_from_these_activities_to_qtl_s_qtl_review_processes,
    x10_how_does_your_company_document_your_risk_based_approaches_to_quality_please_check_all_that_apply_the_goal_of_this_question_and_others_that_follow_with_similar_activities_regarding_ctq_s_qbd_is_to_understand_what_and_how_your_company_makes_links_if_any_from_these_activities_to_qtl_s_qt_ls_aligned_with_ct_qs,
    x10_how_does_your_company_document_your_risk_based_approaches_to_quality_please_check_all_that_apply_the_goal_of_this_question_and_others_that_follow_with_similar_activities_regarding_ctq_s_qbd_is_to_understand_what_and_how_your_company_makes_links_if_any_from_these_activities_to_qtl_s_frequency_of_qtl_review,
    x10_how_does_your_company_document_your_risk_based_approaches_to_quality_please_check_all_that_apply_the_goal_of_this_question_and_others_that_follow_with_similar_activities_regarding_ctq_s_qbd_is_to_understand_what_and_how_your_company_makes_links_if_any_from_these_activities_to_qtl_s_communication_of_qtl_breaches,
    x10_how_does_your_company_document_your_risk_based_approaches_to_quality_please_check_all_that_apply_the_goal_of_this_question_and_others_that_follow_with_similar_activities_regarding_ctq_s_qbd_is_to_understand_what_and_how_your_company_makes_links_if_any_from_these_activities_to_qtl_s_implementation_of_corrective_actions,
    x10_how_does_your_company_document_your_risk_based_approaches_to_quality_please_check_all_that_apply_the_goal_of_this_question_and_others_that_follow_with_similar_activities_regarding_ctq_s_qbd_is_to_understand_what_and_how_your_company_makes_links_if_any_from_these_activities_to_qtl_s_reporting_significant_qtl_deviations_in_csr
  )


# Question 18 ----   
q18_raw <- raw_data |> 
  select(
    x18_how_are_qtl_s_governed_utilized_at_your_company_please_check_all_that_apply_formally_integrated_in_qms_health_authority_inspection,
    x18_how_are_qtl_s_governed_utilized_at_your_company_please_check_all_that_apply_formally_integrated_in_qms_continuous_improvement_e_g_future_protocol_development_process_improvement_activities,
    x18_how_are_qtl_s_governed_utilized_at_your_company_please_check_all_that_apply_formally_integrated_in_qms_submissions,
    x18_how_are_qtl_s_governed_utilized_at_your_company_please_check_all_that_apply_formally_integrated_in_qms_senior_management_review,
    x18_how_are_qtl_s_governed_utilized_at_your_company_please_check_all_that_apply_formally_integrated_in_qms_quality_management_oversight_e_g_gcp_quality_councils_committees,
    x18_how_are_qtl_s_governed_utilized_at_your_company_please_check_all_that_apply_formally_integrated_with_quality_by_design_processes,
    x18_how_are_qtl_s_governed_utilized_at_your_company_please_check_all_that_apply_formally_integrated_with_critical_to_quality_processes,
    x18_how_are_qtl_s_governed_utilized_at_your_company_please_check_all_that_apply_other_please_specify_below,
  )



# Question 19 ----   

### |- UPDATED -----

q19_raw <- raw_data |> 
  select(
    x19_what_types_of_actions_has_your_company_typically_taken_or_plan_to_take_in_response_to_a_qtl_breach_please_provide_one_response_per_possible_action_protocol_amendment,
    x19_what_types_of_actions_has_your_company_typically_taken_or_plan_to_take_in_response_to_a_qtl_breach_please_provide_one_response_per_possible_action_change_in_qtl_threshold_s_resetting,
    x19_what_types_of_actions_has_your_company_typically_taken_or_plan_to_take_in_response_to_a_qtl_breach_please_provide_one_response_per_possible_action_change_in_qtl_parameter_metric,
    x19_what_types_of_actions_has_your_company_typically_taken_or_plan_to_take_in_response_to_a_qtl_breach_please_provide_one_response_per_possible_action_change_in_qtl_statistical_distribution,
    x19_what_types_of_actions_has_your_company_typically_taken_or_plan_to_take_in_response_to_a_qtl_breach_please_provide_one_response_per_possible_action_change_in_qtl_statistical_methodology,
    x19_what_types_of_actions_has_your_company_typically_taken_or_plan_to_take_in_response_to_a_qtl_breach_please_provide_one_response_per_possible_action_change_to_trial_monitoring_strategy,
    x19_what_types_of_actions_has_your_company_typically_taken_or_plan_to_take_in_response_to_a_qtl_breach_please_provide_one_response_per_possible_action_instruction_s_provided_to_sites,
    x19_what_types_of_actions_has_your_company_typically_taken_or_plan_to_take_in_response_to_a_qtl_breach_please_provide_one_response_per_possible_action_instruction_s_provided_to_vendors_service_providers_or_otherwise,
    x19_what_types_of_actions_has_your_company_typically_taken_or_plan_to_take_in_response_to_a_qtl_breach_please_provide_one_response_per_possible_action_other_please_specify_below,
    your_response_and_possible_action_comments
  )



# Question 20.3 ----   

### |- UPDATED -----

q20.3_raw <- raw_data |> 
  select(
    x20_3_if_qtl_primary_limit_breaches_are_evaluated_for_importance_how_do_you_determine_as_to_whether_they_should_be_reported_in_the_csr,
    other_6
  )


# Question 23 ----      

### |- UPDATED -----

# |- status ----
q23_raw <- raw_data |> 
  select(
   x23_please_indicate_below_the_possible_potential_parameters_for_qt_ls_as_defined_by_trans_celerate_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_24_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_protocol_deviation_inclusion_exclusion_criteria,
   x23_please_indicate_below_the_possible_potential_parameters_for_qt_ls_as_defined_by_trans_celerate_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_24_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_protocol_deviation_study_conduct,
   x23_please_indicate_below_the_possible_potential_parameters_for_qt_ls_as_defined_by_trans_celerate_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_24_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_protocol_deviation_other,
   x23_please_indicate_below_the_possible_potential_parameters_for_qt_ls_as_defined_by_trans_celerate_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_24_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_primary_endpoint_assessement,
   x23_please_indicate_below_the_possible_potential_parameters_for_qt_ls_as_defined_by_trans_celerate_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_24_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_secondary_endpoint_assessment,
   x23_please_indicate_below_the_possible_potential_parameters_for_qt_ls_as_defined_by_trans_celerate_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_24_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_investigational_product_compliance,
   x23_please_indicate_below_the_possible_potential_parameters_for_qt_ls_as_defined_by_trans_celerate_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_24_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_investigational_product_other,
   x23_please_indicate_below_the_possible_potential_parameters_for_qt_ls_as_defined_by_trans_celerate_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_24_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_randomization_failure,
   x23_please_indicate_below_the_possible_potential_parameters_for_qt_ls_as_defined_by_trans_celerate_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_24_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_lost_to_follow_up,
   x23_please_indicate_below_the_possible_potential_parameters_for_qt_ls_as_defined_by_trans_celerate_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_24_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_informed_consent,
   x23_please_indicate_below_the_possible_potential_parameters_for_qt_ls_as_defined_by_trans_celerate_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_24_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_ae_sae_reporting,
   x23_please_indicate_below_the_possible_potential_parameters_for_qt_ls_as_defined_by_trans_celerate_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_24_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_censored_data_trial_participants_censored_for_primary_objective_statistical_analysis,
   x23_please_indicate_below_the_possible_potential_parameters_for_qt_ls_as_defined_by_trans_celerate_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_24_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_disposition_early_termination_from_study_drug,
   x23_please_indicate_below_the_possible_potential_parameters_for_qt_ls_as_defined_by_trans_celerate_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_24_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_repeated_measures_timepoints_for_fih_early_phase_trials,
   x23_please_indicate_below_the_possible_potential_parameters_for_qt_ls_as_defined_by_trans_celerate_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_24_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_stratification,
   x23_please_indicate_below_the_possible_potential_parameters_for_qt_ls_as_defined_by_trans_celerate_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_24_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_other_1_please_specify_below,
   x23_please_indicate_below_the_possible_potential_parameters_for_qt_ls_as_defined_by_trans_celerate_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_24_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_other_2_please_specify_below,
   x23_please_indicate_below_the_possible_potential_parameters_for_qt_ls_as_defined_by_trans_celerate_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_24_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_other_3_please_specify_below,
   other_1,
   other_2_2
  )



# |- rate ----

### |- UPDATED -----

q23_rate_raw <- raw_data |> 
  select(
    x24_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_protocol_deviation_inclusion_exclusion_criteria,
    x24_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_protocol_deviation_study_conduct,
    x24_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_protocol_deviation_other,
    x24_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_primary_endpoint_assessment,
    x24_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_secondary_endpoint_assessment,
    x24_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_investigational_product_compliance,
    x24_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_investigational_product_other,
    x24_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_randomization_failure,
    x24_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_lost_to_follow_up,
    x24_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_informed_consent,
    x24_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_ae_sae_reporting,
    x24_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_censored_data_trial_participant_censored_for_primary_objectives_statistical_analysis,
    x24_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_disposition_early_termination_from_study_drug,
    x24_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_repeated_measures_timepoints_for_fih_early_phase_trials,
    x24_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_stratification,
    x24_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_other_1,
    x24_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_other_2,
    x24_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_other_3,
  )



  
# Question 24 ----      

# |- status ----
q24_raw <- raw_data |> 
  select(
    x25_please_indicate_if_any_of_the_below_additional_parameters_are_also_considered_as_parameters_for_qt_ls_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_26_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_crf_transcription_errors,
    x25_please_indicate_if_any_of_the_below_additional_parameters_are_also_considered_as_parameters_for_qt_ls_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_26_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_tmf_completeness,
    x25_please_indicate_if_any_of_the_below_additional_parameters_are_also_considered_as_parameters_for_qt_ls_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_26_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_tmf_quality,
    x25_please_indicate_if_any_of_the_below_additional_parameters_are_also_considered_as_parameters_for_qt_ls_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_26_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_vendor_oversight,
    x25_please_indicate_if_any_of_the_below_additional_parameters_are_also_considered_as_parameters_for_qt_ls_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_26_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_ae_sae_management,
    x25_please_indicate_if_any_of_the_below_additional_parameters_are_also_considered_as_parameters_for_qt_ls_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_26_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_data_entry_timeliness,
    x25_please_indicate_if_any_of_the_below_additional_parameters_are_also_considered_as_parameters_for_qt_ls_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_26_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_data_processing_querying,
    x25_please_indicate_if_any_of_the_below_additional_parameters_are_also_considered_as_parameters_for_qt_ls_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_26_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_asset_compound_specific,
    x25_please_indicate_if_any_of_the_below_additional_parameters_are_also_considered_as_parameters_for_qt_ls_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_26_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_therapeutic_area_specific,
    x25_please_indicate_if_any_of_the_below_additional_parameters_are_also_considered_as_parameters_for_qt_ls_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_26_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_indication_specific,
    x25_please_indicate_if_any_of_the_below_additional_parameters_are_also_considered_as_parameters_for_qt_ls_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_26_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_protocol_specific,
    x25_please_indicate_if_any_of_the_below_additional_parameters_are_also_considered_as_parameters_for_qt_ls_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_26_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_other_1_please_specify_below,
    x25_please_indicate_if_any_of_the_below_additional_parameters_are_also_considered_as_parameters_for_qt_ls_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_26_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_other_2_please_specify_below,
    x25_please_indicate_if_any_of_the_below_additional_parameters_are_also_considered_as_parameters_for_qt_ls_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_question_26_disclaimer_this_is_not_considered_a_definitive_list_of_potential_parameters_and_may_be_interpreted_differently_between_responders_other_3_please_specify_below,
    other_1_2
    )
 

### |- UPDATED -----

# |- rate ----
q24_rate_raw <- raw_data |> 
  select(
    x26_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_crf_transcription_errors,
    x26_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_tmf_completeness,
    x26_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_tmf_quality,
    x26_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_vendor_oversight,
    x26_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_ae_sae_management,
    x26_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_data_entry_timeliness,
    x26_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_data_processing_querying,
    x26_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_asset_compound_specific,
    x26_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_therapeutic_area_specific,
    x26_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_indication_specific,
    x26_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_protocol_specific,
    x26_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_other_1,
    x26_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_other_2,
    x26_please_rate_on_a_scale_of_1_low_2_medium_or_3_high_the_perceived_value_of_the_parameter_used_other_3
  )




